### PR TITLE
1.18.2 gnifty

### PR DESCRIPTION
**Pull request by gniftygnome**
Here's a proposal for 1.18.2 generation.  It's kind of a hack but it's a really simple one.  We just apply an overlay to the VanillaBiomeParameters to replace a portion of the noise points for the target biomes with ours.  Although it looks a bit different from "standard" biome placement, I think it is pretty good considering.  It also has the benefit of being very compatible with other biome mods (at worst, ours just won't generate).

I have also cleaned up dead code and broken the project up into common, client, and worldgen modules as suggested in Discord.  There are some more cleanup type things to do, but I think this is a lot closer to production-ready.  Also, world generation can be disabled by commenting out `include "worldgen"` in `settings.gradle`.

### CODE REVIEW

**Comment by gniftygnome** [comment]
BTW this includes #85.

**Comment by oliviathevampire** [comment]
Why can you just not use Terrablender instead of making custom code for the biome stuff? will also make this more compatible with other biome mods

**Comment by gniftygnome** [comment]
> Why can you just not use Terrablender

The original 1.18.2 PRs for both Traverse and Terrestria used TerraBlender.  It is roughly trivial to revert to use TerraBlender.  However, the sense I have from the Terraformers folks is they would prefer not to.  Personally, I do not have a strong preference either way.  My preference is to do whatever will help get an official release out.

To be clear, though, it is not the case that TerraBlender has better mod compatibility.  It has *different* mod compatibility.  Also, it does not use yarn mappings, which likely means it will never become a standard for the fabric community (unless that changes).

**Comment by gniftygnome** [comment]
> Why can you just not use Terrablender

Breaking news!  That's what we're going to do.  :)  Sorry for the whiplash.

**Pull request merged**
